services:
    db:
        env_file:
          - .env
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1433:1433
        volumes:             
            - ./init:/docker-entrypoint-initdb.d
        environment:
            SA_PASSWORD: "${DB_PASSWORD}"
            ACCEPT_EULA: "Y"
    icarus:
        build: .   
